application:
  version: 1.0.0
spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db-konkuk-project.cy8bbga73uwg.ap-northeast-2.rds.amazonaws.com:3306/dev_yj_db?serverTimezone=Asia/Seoul
    username: admin
    password: konkukpw2022

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true

server:
  port: 3000  # 3000번 포트로 실행

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace